/* MyPage auto-generated by npm run generator */
import { RouteComponentProps } from "@reach/router"
import { Theme } from "@material-ui/core"
import { makeStyles, CSSProperties } from "@material-ui/styles"
import { observer } from "mobx-react"
import React from "react"
import Store from "store/Store"
import { useRootClasses } from "style"
import { observable } from "mobx"

interface MyPageProps {}

const useStyles = makeStyles((theme: Theme) => ({
    myPagePage: {}
}))

class MyPageState {
    @observable
    componentName = "MyPage"
}

const MyPage: React.FC<RouteComponentProps<MyPageProps>> = props => {
    const classes = useStyles()
    const rc = useRootClasses()
    const state = React.useRef(new MyPageState).current

    return (
        <div className={classes.myPagePage}>
            MyPage Page
        </div>
    )
}

export default observer(MyPage)