/* Apple auto-generated by npm run generator */
import { Theme } from "@material-ui/core"
import { makeStyles, CSSProperties } from "@material-ui/styles"
import { observer } from "mobx-react"
import clsx from "clsx"
import React from "react"
import Store from "store/Store"
import { useRootClasses } from "style"
import { observable } from "mobx"

interface AppleProps {
    className?: string
    style?: CSSProperties
    children?: React.ReactNode
}

class AppleState {
    @observable
    componentName = "Apple"
}

const useStyles = makeStyles((theme: Theme) => ({
    fruitAppleAtom: {}
}))

const Apple: React.FC<AppleProps> = props => {
    const classes = useStyles()
    const rc = useRootClasses()
    const className = clsx(classes.fruitAppleAtom, props.className)
    const state = React.useRef(new AppleState).current

    return (
        <div className={className} style={props.style}>
            {props.children}
        </div>
    )
}

export default observer(Apple)