/* ProjectPicker auto-generated by npm run generator */
import { Theme } from "@material-ui/core"
import { makeStyles, CSSProperties } from "@material-ui/styles"
import { observer } from "mobx-react"
import clsx from "clsx"
import React from "react"
import Store from "store/Store"
import { useRootClasses } from "style"
import Btn from "components/atoms/Btn"

interface ProjectPickerProps {
    className?: string
    style?: CSSProperties
    children?: React.ReactNode
}

const useStyles = makeStyles((theme: Theme) => ({
    projectPickerOrganism: {}
}))

const ProjectPicker: React.FC<ProjectPickerProps> = props => {
    const classes = useStyles()
    const rc = useRootClasses()
    const className = clsx(classes.projectPickerOrganism, props.className, rc.column)

    const rows = Store.distributedLock.state.projects.map((project, idx) => {
        return (
            <Btn
                key={idx}
                variant={project === Store.distributedLock.state.selectedProject ? "contained" : "outlined"}
                onClick={() => Store.distributedLock.actions.setProject(project)}
            >
                {project}
            </Btn>
        )
    })

    return (
        <div className={className} style={props.style}>
            <h5>Choose a Project:</h5>
            {rows}
            <Btn className={rc.mt2} onClick={() => Store.distributedLock.actions.createProject()}>
                + Create
            </Btn>
        </div>
    )
}

export default observer(ProjectPicker)
